### ISSUE TITLE
initial data processing script

### ISSUE THREAD

**Issue by dcherian** [OceanMixingGroup/chipod_gust#35]
Writing here so I don't forget.

Just as you were saying, it would be useful to have a script that

1. averages raw χpod data and generates `temp.mat`
2. optionally averages raw pitot data and generated `Praw.mat`
3. optionally generates `dTdz_i.mat`
4. uses the averaged data to generate summary plots (entire time series)
5. generates summary plots that zoom in on consecutive short intervals (e.g. 3 weeks). This would be useful for finding problems in long deployments.

**Comment by jbecherer** [comment]
Maybe instead of having 3 week intervals it could be a flexible parameter, so in case you have shorter deployments you could also break those further up.

**Comment by dcherian** [comment]
Ya, it would be configurable.
