### ISSUE TITLE
better naming of chi-estimate permutations

### ISSUE THREAD

**Issue by dcherian** [OceanMixingGroup/chipod_gust#6]
I think it would be less confusing if we used 'T' to indicate which temperature timeseries is being used; so the names would become

```
mm1 -> mmT1
pi11 -> pi1T1
pi212 -> pi2T12
```

If you agree, I can write a pull request to rename them.
If you think it's not worth the effort, fine by me.

**Comment by jbecherer** [comment]
not sure. 
I just wrote a readme field to the 
final Turb.mat, which tries to explain all the fields.

**Comment by jbecherer** [comment]
In the end, I am not sure if the extra T really helps if you don't have a clue.

**Comment by jbecherer** [comment]
I guess the aim should rather be to write a proper documentation that people could use
to look it up if they are unsure.

**Comment by dcherian** [comment]
Sounds good.
